### PR TITLE
Patch 05 2022

### LINKED ISSUE #878: 2D map views are not coloured / set up correctly
**Describe the bug**
2D map plotting (e.g. in the distance vs angle map of the `CalculateDAngle` module) currently assumes a flat XZ view, and which is coloured completely black. Obviously this hides the detail in the data, so:

- [ ] Default to a 3D view where necessary, and perhaps set a better default viewing angle to as to see the actual data
- [ ] Fix colouring of data

### PR DESCRIPTION
**Pull request by trisyoungs**
Patch PR addressing a batch of small fixes, corrections, and improvements.

Closes #878.

### CODE REVIEW

File: src/classes/species_atomic.cpp [hunk 1]
```diff
@@ -301,21 +302,11 @@ int Species::simplifyAtomTypes()
...
-            {
-                Messenger::warn(
-                    "No atom type assigned to atom index {} in species '{}', so can't calculate correct total charge.\n",
-                    i.userIndex(), name_);
-                continue;
-            }
-            totalQ += i.atomType()->charge();
-        }
+        return std::accumulate(atoms_.begin(), atoms_.end(), 0.0, [](const auto acc, const auto &i) {
+            return acc + (i.atomType() ? i.atomType()->charge() : 0.0);
```
Comment (rprospero) [inline src/classes/species_atomic.cpp:307]: Very nice

**Review by rprospero — APPROVED** [review]
