### PR TITLE
Site Crashes

### LINKED ISSUE #1504: Crashing when creating static/fragment sites
When creating a `Static` or `Fragment` site, crashes occur. In the case of `Static` sites, this occurs if you create a new site and then set X-axis atoms. With `Fragment` sites, this occurs if you have a description without any origin tags (such as the empty string!). This does seem to be GUI related issue.

### PR DESCRIPTION
**Pull request by jws-1**
Small PR to fix some *dumb* mistakes causing crashes when adding/creating `Static`/`Fragment` sites. Closes #1504.

### CODE REVIEW

File: src/classes/speciesSite.cpp [hunk 1]
```diff
@@ -70,7 +70,7 @@ SpeciesSite::SiteType SpeciesSite::type() const { return type_; }
 // Return whether the site has defined axes sites
 bool SpeciesSite::hasAxes() const
 {
-    return (type_ == SiteType::Static && !(staticXAxisAtoms_.empty() && staticYAxisAtoms_.empty())) ||
+    return (type_ == SiteType::Static && !(staticXAxisAtoms_.empty() || staticYAxisAtoms_.empty())) ||
```
Comment (trisyoungs) [inline src/classes/speciesSite.cpp:73]: I did look at this logic first time around, but also didn't quite process it right!

**Review by trisyoungs — APPROVED** [review]

File: src/classes/speciesSite.cpp (hunk 1 above)
Comment (jws-1) [reply src/classes/speciesSite.cpp:73]: Yep... not sure what happened with either of us there!
