### PR TITLE
Empty Expressions

### LINKED ISSUE #1487: Empty Expressions
**Describe the bug**
An empty expression (often) causes a segmentation fault.

**To Reproduce**
1. Add a node to a procedure that uses a `NodeValueKeyword` (e.g. `CustomRegion`), i.e. allows an expression to be entered.
2. Empty the text edit of the keyword and press enter.
3. Segmentation fault.

**Expected behaviour**
Not to segfault, should instead indicate that the expression is invalid.

**Operating System:**
 - OS: Linux
 - OS version / flavour: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jws-1**
This slightly-hacky PR prevents segmentation faults occurring when expression strings in nodes are empty. Closes #1487.

### CODE REVIEW

**Comment by trisyoungs** [comment]
Ignoring the swathe of broken unit tests for now (:grin:) I can also segfault Dissolve as simply as adding in a rogue backtick on to an expression, for example adding one on to the end of `rho` in my `AddNode` density keyword (heh - overly descriptive: try getting a backtick to display in code in a comment!) I get a `throw` of "Failed to evaluate expression ''.".  This shows up correctly as a red cross in the GUI, but is blindly ignored when you run the procedure.  So this is a bigger problem than perhaps anticipated.

I think the neatest solution would be to extend the `ProcedureNodeSequence::check()` to check any `NodeValue`-based keywords on each node for validity, calling the `check()` function before the procedure is executed.

**Comment by jws-1** [comment]
> Ignoring the swathe of broken unit tests for now (grin) I can also segfault Dissolve as simply as adding in a rogue backtick on to an expression, for example adding one on to the end of `rho` in my `AddNode` density keyword (heh - overly descriptive: try getting a backtick to display in code in a comment!) I get a `throw` of "Failed to evaluate expression ''.". This shows up correctly as a red cross in the GUI, but is blindly ignored when you run the procedure. So this is a bigger problem than perhaps anticipated.
> 
> I think the neatest solution would be to extend the `ProcedureNodeSequence::check()` to check any `NodeValue`-based keywords on each node for validity, calling the `check()` function before the procedure is executed.

While that does seem to solve the `backtick` problem, it doesn't solve the issue of empty expressions and expressions with periods and no numbers. Both issues occur as `isNumber` returns true, and then `std::stod` and `std::stoi` throw `std::invalid_argument`.

File: src/procedure/nodes/sequence.cpp [hunk 1]
```diff
@@ -401,6 +401,11 @@ bool ProcedureNodeSequence::check() const
         // Check node branch if present
         if (node->branch() && !node->branch()->get().check())
             return false;
+
+        // Check validity of NodeValue-based keywords
+        for (auto &kwd : node->keywords().allOfType<NodeValue>())
+            if (!kwd->isValid())
+                return false;
```
Comment (trisyoungs) [inline src/procedure/nodes/sequence.cpp:408]: Just adding a couple of other `NodeValue`-based classes, and to note that these must reference the keyword class, not the datatype.  Code not tested, BTW!
```suggestion

        // Check validity of NodeValue-based keywords
        for (auto &kwd : node->keywords().allOfType<NodeValueKeyword>())
            if (!kwd->data().isValid())
                return false;
        for (auto &kwd : node->keywords().allOfType<Vec3NodeValueKeyword>())
            if (!kwd->data().x.isValid() || !kwd->data().y.isValid() || !kwd->data().z.isValid())
                return false;
        for (auto &kwd : node->keywords().allOfType<NodeValueEnumOptionsBaseKeyword>())
            if (!kwd->value().isValid())
                return false;
```

**Review by trisyoungs — CHANGES_REQUESTED** [review]

File: src/procedure/nodes/sequence.cpp (hunk 1 above)
Comment (jws-1) [reply src/procedure/nodes/sequence.cpp:408]: Oops.. still familiarising myself with the `NodeValue` stuff.

File: src/base/sysFunc.cpp [hunk 2]
```diff
@@ -290,11 +291,13 @@ bool DissolveSys::isNumber(std::string_view text, bool &isFloatingPoint)
                 // If not a digit, return false
                 if (!isdigit(c))
                     return false;
+                ++nDigits;
                 break;
         }
     }
 
-    return true;
+    isFloatingPoint &= nDigits > 0;
```
Comment (trisyoungs) [inline src/base/sysFunc.cpp:299]: Bit witchcraft!

**Review by trisyoungs — APPROVED** [review]
:+1:
