### PR TITLE
Input File Writing

### LINKED ISSUE #743: Improper Term description not writing correctly
**Describe the bug**
When writing an input file containing 'Improper' terms in the MasterTerms tab, the input file is not writing correctly, and missing the first character of the 2nd, 3rd and 4th atom type involved.

For example:

```
  Improper  'C_R- _R- _m_2- _m_2'  FourierN    25.104     1.000    -1.000     0.000
  Improper  'C_R- _R- _R- _R'  FourierN    25.104     1.000    -1.000     0.000
  Improper  'C_R- _- _R- _R'  FourierN    25.104     1.000    -1.000     0.000
```
when it should be

```
  Improper  'C_R-C_R-O_m_2-O_m_2'  FourierN    25.104     1.000    -1.000     0.000
  Improper  'C_R-C_R-C_R-C_R'  FourierN    25.104     1.000    -1.000     0.000
  Improper  'C_R-H_-C_R-C_R'  FourierN    25.104     1.000    -1.000     0.000
```

The 'C' is a blank space

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
1. Generate a structure with improper terms
2. Apply forcefield
3. Save input file
4. Re-load the input file in GUI and met with error
5. View missing characters in input .txt file

I have only encountered this issue on the 0.9.0 continuous build so far - specific PR version is 22ab020

There may not be need to assign the forcefield to the molecule, but rather when generating the improper torsion terms in the molecule initially, the issue first occurs.

**Operating System:**
 - OS:  Windows 10

### PR DESCRIPTION
**Pull request by trisyoungs**
This PR addresses a few issues related to writing of terms to the input file.

- A new lambda-enabled overload of the `joinStrings` algorithm has been added to increase flexibility and address writing of incorrect site origin/axis atom indices.
- Improper master term names were generated from a `std::vector` of `std::string_view` constructed from in-place initialised `std::string`s, which presumably causes #743.

Closes #743.

### CODE REVIEW

File: src/templates/algorithms.h [hunk 1]
```diff
@@ -235,12 +235,24 @@ template <typename Iterator> std::string joinStrings(Iterator begin, Iterator en
...
-// Join the parameters into a comma separated string
+template <typename Iterator, class Lam> std::string joinStrings(Iterator begin, Iterator end, std::string delim, Lam lambda)
+{
+    if (begin == end)
+        return std::string();
+    std::stringstream stream;
+    stream << fmt::format("{}", lambda(*begin));
+    std::for_each(std::next(begin), end,
+                  [&stream, &lambda, &delim](const auto value) { stream << delim << fmt::format("{}", lambda(value)); });
+    return stream.str();
```
Comment (rprospero) [inline src/templates/algorithms.h:246]: We can get rid of some of these overloads with C++ and the `identity` function when we move to C++20, but this is the best we can do for now.

**Review by rprospero — APPROVED** [review]
