### PR TITLE
Forcefield Wizard Fixes

### LINKED ISSUE #1106: Added impropers are not listed in Add Forcefield Wizard
**Describe the bug**
In the Add Forcefield Wizard, the intramolecular term conflicts page displays bond, angle, torsion, but not improper terms.

### LINKED ISSUE #1107: Existing (master) terms not overwritten
**Describe the bug**
It looks like the Add Forcefield Wizard suggests that term data will be overwritten if naming conflicts are discovered, but in practice this does not occur for (at least) master terms.

### LINKED ISSUE #1135: Crash when run Ar example tutorial - and set up forcefield
**Describe the bug**
Running version 0.9.1 and on windows 10. 

**To Reproduce**
See below

ar_dissolve

### PR DESCRIPTION
**Pull request by trisyoungs**
This PR patches up some issues with the `AddForcefieldTerms` wizard.

Closes #1106.
Closes #1107.
Closes #1135.

### CODE REVIEW

File: src/gui/addforcefieldtermsdialog_funcs.cpp [hunk 1]
```diff
@@ -44,18 +44,19 @@ AddForcefieldTermsDialog::AddForcefieldTermsDialog(QWidget *parent, Dissolve &di
...
             this, SLOT(masterTermSelectionChanged(const QItemSelection &, const QItemSelection &)));
 
     // Set initial state of controls
-    if (!targetSpecies_->selectedAtoms().empty())
-    {
-        ui_.AtomTypesAssignSelectionRadio->setChecked(true);
-        ui_.IntramolecularTermsAssignSelectionRadio->setChecked(true);
-    }
+    ui_.AtomTypesAssignSelectionRadio->setEnabled(!targetSpecies_->selectedAtoms().empty());
+    ui_.IntramolecularTermsAssignSelectionRadio->setEnabled(!targetSpecies_->selectedAtoms().empty());
```
Comment (rprospero) [inline src/gui/addforcefieldtermsdialog_funcs.cpp:59]: Obviously the better solution

File: src/gui/addforcefieldtermsdialog_funcs.cpp [hunk 2]
```diff
@@ -425,36 +429,21 @@ bool AddForcefieldTermsDialog::assignIntramolecularTerms(const Forcefield *ff)
...
-            break;
-        }
+    auto conflicts = std::any_of(temporaryCoreData_.masterBonds().begin(), temporaryCoreData_.masterBonds().end(),
+                                 [&](const auto &i) { return dissolve_.coreData().getMasterBond(i->name()); }) ||
+                     std::any_of(temporaryCoreData_.masterAngles().begin(), temporaryCoreData_.masterAngles().end(),
+                                 [&](const auto &i) { return dissolve_.coreData().getMasterAngle(i->name()); }) ||
+                     std::any_of(temporaryCoreData_.masterTorsions().begin(), temporaryCoreData_.masterTorsions().end(),
+                                 [&](const auto &i) { return dissolve_.coreData().getMasterTorsion(i->name()); }) ||
+                     std::any_of(temporaryCoreData_.masterImpropers().begin(), temporaryCoreData_.masterImpropers().end(),
+                                 [&](const auto &i) { return dissolve_.coreData().getMasterImproper(i->name()); });
```
Comment (rprospero) [inline src/gui/addforcefieldtermsdialog_funcs.cpp:439]: Very nice construct here

**Review by rprospero — APPROVED** [review]
On obvious improvement on all fronts.
