### PR TITLE
Remove nodes

### LINKED ISSUE #1420: Can't remove nodes from procedures
**Describe the bug**
It is currently not possible to remove nodes from procedures in the GUI.

That's it!

### PR DESCRIPTION
**Pull request by jws-1**
This PR adds the ability to remove nodes from a procedure. Closes #1420.

### CODE REVIEW

File: src/gui/procedureWidgetFuncs.cpp [hunk 1]
```diff
@@ -175,6 +175,18 @@ void ProcedureWidget::on_AvailableNodesTree_doubleClicked(const QModelIndex &ind
...
 
+void ProcedureWidget::on_DeleteNodeButton_clicked(bool checked)
+{
+    auto selected = ui_.NodesTree->selectionModel()->selectedIndexes();
+    if (selected.size() > 0)
+    {
+        auto node = procedureModel_.data(selected.at(0), Qt::UserRole).value<std::shared_ptr<ProcedureNode>>();
+        assert(node);
+        procedure_.value().get().removeNode(node);
+        updateNodeTree();
```
Comment (trisyoungs) [inline src/gui/procedureWidgetFuncs.cpp:186]: Ah, you see what you've done here is opened up a nasty can of worms for yourself! Unfortunately it's bad practice to remove the node from the procedure directly like this, since our widget is guided by a model (`ProcedureModel` in `src/gui/models/procedureModel.cpp` - already loving the new naming scheme!). That means that to ensure correctness we need to delete the node via the model itself so it understands what has changed. This would also emit `dataChanged` so that other keywords in the procedure are updated following (potentially) the removal of a node that one or more of them referenced.

File: src/gui/procedureWidgetFuncs.cpp [hunk 2]
```diff
@@ -175,6 +175,18 @@ void ProcedureWidget::on_AvailableNodesTree_doubleClicked(const QModelIndex &ind
...
+    }
```
Comment (trisyoungs) [inline src/gui/procedureWidgetFuncs.cpp:187]: As a related issue, once a node has been deleted the controls are still displayed for it, and no node ends up being selected in the tree.

**Review by trisyoungs — CHANGES_REQUESTED** [review]
Good start, but it's time to revisit (and re-despise) Qt's Model-View framework I'm afraid!

File: src/gui/procedureWidgetFuncs.cpp (hunk 1 above)
Comment (jws-1) [reply src/gui/procedureWidgetFuncs.cpp:186]: Of course.. Luckily I have plenty of experience with models!

File: src/gui/models/procedureModel.cpp [hunk 3]
```diff
@@ -5,6 +5,7 @@
 #include "gui/models/procedureModelMimeData.h"
 #include "procedure/nodes/registry.h"
 #include "procedure/procedure.h"
+#include "qabstractitemmodel.h"
```
Comment (trisyoungs) [inline src/gui/models/procedureModel.cpp:8]: Not sure why this `#include` is here?  I don't need it on my system, and it's also a system header being included in quotes rather than `<>`. VS to blame?

File: src/gui/procedureWidget.h [hunk 4]
```diff
@@ -60,6 +60,7 @@ class ProcedureWidget : public QWidget
     void updateNodeTree();
     void on_NodesTree_customContextMenuRequested(const QPoint &pos);
     void on_AvailableNodesTree_doubleClicked(const QModelIndex &index);
+    void on_DeleteNodeButton_clicked(bool checked);
```
Comment (trisyoungs) [inline src/gui/procedureWidget.h:63]: Bug :lady_beetle: report!  If I click the delete node button when the list is empty (or presumably when no node is selected) I get a segfault.  May be nicer UX to disable the button if no node is selected.

File: src/gui/models/procedureModel.cpp [hunk 5]
```diff
@@ -461,3 +462,19 @@ bool ProcedureModel::insertRows(int row, int count, const QModelIndex &parent)
...
+        return false;
+
+    // Get the scope associated to the parent index
+    auto scope = getScope(parent);
+
+    beginRemoveRows(parent, row, row + count - 1);
+    for (auto i = 0; i < count; ++i)
+        scope->get().removeNode(data(index(row + i, 0), Qt::UserRole).value<std::shared_ptr<ProcedureNode>>());
+    endRemoveRows();
+
```
Comment (trisyoungs) [inline src/gui/models/procedureModel.cpp:478]: Need to emit `dataChanged` otherwise we don't properly update other things.
```suggestion

    emit(dataChanged(QModelIndex(), QModelIndex());
```

Furthermore, need to call `updateControls()` in `ProcedureWidget::procedureDataChanged()` (line 134) since the relationships between data are validated by the function, but the incorrect values are still displayed in the current control widget because we don't update it.

File: src/gui/models/procedureModel.cpp (hunk 3 above)
Comment (jws-1) [reply src/gui/models/procedureModel.cpp:8]: That'd be my neovim LSP config to blame!

Comment (trisyoungs) [reply src/gui/models/procedureModel.cpp:8]: Why am I only just hearing about `neovim`? :disappointed:

**Review by trisyoungs — APPROVED** [review]
Looks good, works nicely!  I'm obliged to mention for the general record that the inability to undo a node deletion (or addition, or move, or keyword change...) is a bit of an issue. So, while we are not using TOML for input file I/O immediately, it is in our interest to get that up to scratch and compiled as part of the `develop` stream so we can leverage it for undo/redo actions like this.

Aaaaaanyway, that's obviously not in scope for this PR, but I just wanted to write it down!

**Comment by jws-1** [comment]
> Looks good, works nicely! I'm obliged to mention for the general record that the inability to undo a node deletion (or addition, or move, or keyword change...) is a bit of an issue. So, while we are not using TOML for input file I/O immediately, it is in our interest to get that up to scratch and compiled as part of the `develop` stream so we can leverage it for undo/redo actions like this.
> 
> Aaaaaanyway, that's obviously not in scope for this PR, but I just wanted to write it down!

Yes, I thought it might be an issue. I was tempted to include a dialog to validate the user's decision - but I decided it might be a bit annoying!
