### PR TITLE
Static keyword store

### LINKED ISSUE #1121: Crashing when creating Evolution / Analysis layers
**Describe the bug**
When creating an evolution / analysis layer, Dissolve crashes with the following traceback:
```
libc++abi: terminating with uncaught exception of type std::runtime_error: Item of type 'P13Configuration' cannot be set as no suitable type mapping has been registered.
```

**To Reproduce**
1. Create a new file, or load an existing one.
2. Layer -> Create -> Evolution/Analysis-> *
3. Crash.

**Expected behaviour**
Layer to be successfully created, without crashing.

**Operating System:**
 - OS:  OSX
 - OS version / flavour:  Monterey

I should also mention here, that the expected behaviour is produced when testing on IDAaaS.

### LINKED ISSUE #1156: OSX dmg missing antlr4-cppruntime
**Describe the bug**
The OSX dmg file is missing `libantlr4-runtime.4.9.3.dylib` - it is not present in `Frameworks/lib` or anywhere else.

### PR DESCRIPTION
**Pull request by rprospero**
Remove the KeywordTypeMap and explicitly overload the getters and setters.  This should eliminate the issues with the type hashes under clang.  This should close #1121.

Also closes #1156.

### CODE REVIEW

File: src/keywords/store.h [hunk 1]
```diff
@@ -221,15 +143,31 @@ class KeywordStore
...
-    template <class D> D get(std::string_view name) const
-    {
-        auto it = keywords_.find(name);
-        if (it == keywords_.end())
-            throw(std::runtime_error(fmt::format("Data for keyword '{}' cannot be retrieved as it doesn't exist..\n", name)));
 
-        return setters().get<D>(it->second);
-    }
+    /*
+     *
```
Comment (trisyoungs) [inline src/keywords/store.h:148]:
```suggestion
```

File: src/keywords/store.h [hunk 2]
```diff
@@ -221,15 +143,31 @@ class KeywordStore
...
+
+    // retrieve a Configuration by keyword name
+    Configuration *getConfiguration(std::string_view name) const;
+    // retrieve a vector of Configurations by keyword name
+    std::vector<Configuration *> getVectorConfiguration(std::string_view name) const;
+    // retrieve a Species by keyword name
+    const Species *getSpecies(std::string_view name) const;
+    // retrieve a vector of Modules by keyword name
+    std::vector<Module *> getVectorModule(std::string_view name) const;
+    // retrieve an Integer by keyword name
```
Comment (trisyoungs) [inline src/keywords/store.h:168]:
```suggestion
    // Retrieve a Configuration by keyword name
    Configuration *getConfiguration(std::string_view name) const;
    // Retrieve a vector of Configurations by keyword name
    std::vector<Configuration *> getVectorConfiguration(std::string_view name) const;
    // Retrieve a Species by keyword name
    const Species *getSpecies(std::string_view name) const;
    // Retrieve a vector of Modules by keyword name
    std::vector<Module *> getVectorModule(std::string_view name) const;
    // Retrieve an Integer by keyword name
```

File: src/keywords/store.cpp [hunk 3]
```diff
@@ -161,3 +91,94 @@ bool KeywordStore::serialise(LineParser &parser, std::string_view prefix, bool o
...
+}
+// retrieve a vector of Configurations by keyword name
+std::vector<Configuration *> KeywordStore::getVectorConfiguration(std::string_view name) const
+{
+    return getKeyword<ConfigurationVectorKeyword>(keywords_, name)->data();
+}
+// retrieve an Integer by keyword name
+int KeywordStore::getInt(std::string_view name) const { return getKeyword<IntegerKeyword>(keywords_, name)->data(); }
+
+// retrieve a vector of Modules by keyword name
```
Comment (trisyoungs) [inline src/keywords/store.cpp:180]:
```suggestion
// Retrieve a Configuration by keyword name
Configuration *KeywordStore::getConfiguration(std::string_view name) const
{
    return getKeyword<ConfigurationKeyword>(keywords_, name)->data();
}
// Retrieve a Species by keyword name
const Species *KeywordStore::getSpecies(std::string_view name) const
{
    return getKeyword<SpeciesKeyword>(keywords_, name)->data();
}
// Retrieve a vector of Configurations by keyword name
std::vector<Configuration *> KeywordStore::getVectorConfiguration(std::string_view name) const
{
    return getKeyword<ConfigurationVectorKeyword>(keywords_, name)->data();
}
// Retrieve an Integer by keyword name
int KeywordStore::getInt(std::string_view name) const { return getKeyword<IntegerKeyword>(keywords_, name)->data(); }

// Retrieve a vector of Modules by keyword name
```

File: src/gui/menu_configuration.cpp [hunk 4]
```diff
@@ -197,7 +197,7 @@ void DissolveWindow::on_ConfigurationCreateFrameworkAdsorbatesAction_triggered(b
     {
         addNode->keywords().setEnumeration("BoxAction", AddProcedureNode::BoxActionStyle::None);
         addNode->keywords().setEnumeration("Positioning", AddProcedureNode::PositioningType::Region);
-        addNode->keywords().set<std::shared_ptr<RegionProcedureNodeBase>>("Region", regionNode);
```
Comment (trisyoungs) [inline src/gui/menu_configuration.cpp:200]: Well, doesn't that look better!

**Review by trisyoungs — COMMENTED** [review]
Looks great.  The verbosity of the manual definitions is more than made up for by the cleanliness that this approach offers when using it elsewhere in the code.

**Comment by trisyoungs** [comment]
Closes #1156.

**Review by trisyoungs — APPROVED** [review]
