### PR TITLE
Keyword Signals

### LINKED ISSUE #913: Update reference data when changing FT limits
**Describe the bug**
Modules accepting reference data and which Fourier transform that data (principally `NeutronSQ` and `XRaySQ`) need to run the `setUp()` stage when the FT limits and delta are changed, as well as when the filename is edited.

### PR DESCRIPTION
**Pull request by trisyoungs**
This PR attempts to introduce a suitable mechanism for "reacting" to modifications to keywords when those modifications affect underlying data. In particular, data that may have already been created and stored in the main processing list.

A simple and extensible "signal" enum and class is added, and whose enumerations can be set on individual keywords in order to promote the desired effect when caught by the parent `Module` or `Procedure` (although full implementation of the latter will not be performed until editing is moved off of the custom chart classes - #871).

Rather than implement all probable / possible uses of signals in this PR, exemplar signalling is made on the `NeutronSQ` and `XRaySQ` modules (closes #913). Future required uses will be added as and when required locally in other work.

### CODE REVIEW

File: src/keywords/signals.h [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    enum KeywordSignal
+    {
+        ClearData = 1,
+        RecreateRenderables = 2,
+        ReloadExternalData = 4
+    };
+
+    private:
+    // Signals to be emitted (via Qt) when editing this keyword in the GUI
+    int signalMask_{0};
```
Comment (DanNixon) [inline src/keywords/signals.h:28]: I tend to prefer `std::bitset` for things like this.

**Review by DanNixon — APPROVED** [review]

File: src/keywords/signals.h (hunk 1 above)
Comment (trisyoungs) [reply src/keywords/signals.h]: Old habit! Gotta love a lazy `int`...
