### PR TITLE
1227 Reference data G(r)

### LINKED ISSUE #1227: Fourier transform of reference data not visible
**Describe the bug**

In the `NeutronSQ` module (and presumably `XRaySQ` as well) occasionally users notice that the graph displaying the FT of the supplied reference data (i.e. the F(r)) is "broken" in the sense that nothing appears at all.  Internally, this can be causes by NaNs in the data.

I suspect that the issue is related to how we now handle `Configuration` generation - previously this was always performed, but an empty configuration will return a zero atomic number density.  If this is used in the FT then NaNs wlll occur and may be the cause of the issue.

### PR DESCRIPTION
**Pull request by trisyoungs**
This PR addresses #1227, which is a bug caused by a previous PR removing the automatic generation of configuration contents on file load.  Thus, when any module read in from the file tries to Fourier transform associated reference data, the density value retrieved from the associated `Configuration` is zero, leading to divide-by-zero errors in the Fourier transform and subsequent death of any graphed values.

We solve this issue by returning `std::optional<double>` from the relevant density routines, allowing checks against the validity of the value to be made.

Closes #1227.

### CODE REVIEW

File: src/modules/epsr/process.cpp [hunk 1]
```diff
@@ -162,6 +164,8 @@ bool EPSRModule::process(Dissolve &dissolve, const ProcessPool &procPool)
     if (!targetConfiguration_)
         return Messenger::error("No target configuration is set.\n");
 
+    auto rho = *targetConfiguration_->atomicDensity();
```
Comment (rprospero) [inline src/modules/epsr/process.cpp:167]: I feel we should have a check here to return an error message if `rho` does not have a value.

File: src/modules/neutronsq/process.cpp [hunk 2]
```diff
@@ -220,7 +225,7 @@ bool NeutronSQModule::process(Dissolve &dissolve, const ProcessPool &procPool)
     Filters::trim(repGR, referenceFTQMin_.value_or(0.0), ftQMax);
     auto rMin = weightedGR.total().xAxis().front();
     auto rMax = weightedGR.total().xAxis().back();
-    auto rho = rdfModule->effectiveDensity();
+    auto rho = *rdfModule->effectiveDensity();
```
Comment (rprospero) [inline src/modules/neutronsq/process.cpp:228]: Again, we should return an error if rho is unset.

File: src/modules/rdf/functions.cpp [hunk 3]
```diff
@@ -530,7 +540,7 @@ bool RDFModule::sumUnweightedGR(GenericList &processingData, const ProcessPool &
             fingerprint.empty() ? fmt::format("{}", cfg->contentsVersion()) : fmt::format("_{}", cfg->contentsVersion());
 
         // Calculate weighting factor
-        double weight = ((cfgWeight / totalWeight) * cfg->atomicDensity()) / rho0;
+        double weight = ((cfgWeight / totalWeight) * *cfg->atomicDensity()) / rho0;
```
Comment (rprospero) [inline src/modules/rdf/functions.cpp:543]: Error check

File: src/modules/rdf/functions.cpp [hunk 4]
```diff
@@ -517,7 +527,7 @@ bool RDFModule::sumUnweightedGR(GenericList &processingData, const ProcessPool &
 
     // Calculate overall density of combined system
     double rho0 = std::accumulate(configWeights.begin(), configWeights.end(), 0.0, [totalWeight](double acc, auto pair) {
-        return acc + pair.second / totalWeight / pair.first->atomicDensity();
+        return acc + pair.second / totalWeight / pair.first->atomicDensity().value();
```
Comment (rprospero) [inline src/modules/rdf/functions.cpp:530]: Error check, but this is going to be a bit trickier, since it's inside the lambda.  My initial suggestion would be
```suggestion
        if (!acc) return {};
        auto density = pair.first->atomicDensity{};
        if (!density) return {};
        return *acc + pair.second / totalWeight / *density;
```

And then return an error message if the overall accumulate returns null.

File: src/procedure/nodes/add.cpp [hunk 5]
```diff
@@ -329,8 +329,8 @@ bool AddProcedureNode::execute(const ProcedureContext &procedureContext)
         }
     }
 
-    Messenger::print("[Add] New box density is {:e} atoms/Angstrom**3 ({} g/cm3).\n", cfg->atomicDensity(),
-                     cfg->chemicalDensity());
+    Messenger::print("[Add] New box density is {:e} atoms/Angstrom**3 ({} g/cm3).\n", *cfg->atomicDensity(),
+                     *cfg->chemicalDensity());
```
Comment (rprospero) [inline src/procedure/nodes/add.cpp:333]: Switch these to `value_or` so that we can handle a missing rho

**Review by rprospero — CHANGES_REQUESTED** [review]
Just some error handling bits with the optional.  I like the setup, but we might as well take advantage of the information that the optional is giving us.

File: src/gui/configurationtab_funcs.cpp [hunk 6]
```diff
@@ -100,8 +100,11 @@ void ConfigurationTab::updateDensityLabel()
     if (!configuration_)
         ui_.DensityUnitsLabel->setText("N/A");
     else
-        ui_.DensityUnitsLabel->setText(QString::number(
-            ui_.DensityUnitsCombo->currentIndex() == 0 ? configuration_->atomicDensity() : configuration_->chemicalDensity()));
+    {
+        auto rho =
+            ui_.DensityUnitsCombo->currentIndex() == 0 ? configuration_->atomicDensity() : configuration_->chemicalDensity();
+        ui_.DensityUnitsLabel->setText(rho ? QString::number(*rho) : "--");
```
[the remark this answers is not in the document]
Comment (trisyoungs) [reply src/gui/configurationtab_funcs.cpp:106]: Cool feature tho.

File: src/modules/rdf/functions.cpp (hunk 4 above)
Comment (trisyoungs) [reply src/modules/rdf/functions.cpp:530]: Rather than "complicate" the `accumulate` call here, I've elected to perform a direct check in the preceding loop so that no lambda-based check is necessary.
