### PR TITLE
1297 optional keyword exception handling

### LINKED ISSUE #1297: OptionalInt Exception Handling
**Describe the bug**
In 0.9.X a change was made to the `ModifyPotential` keyword of EPSR, moving it from a `bool` to an `OptionalInteger`.  Old input files still containing `False` will silently fail the input file read, annoying the user.

Fix this so that we have considerably more verbosity when a parse error is encountered!

### PR DESCRIPTION
**Pull request by Danbr4d**
Closes #1297. Initial commit for questions

### CODE REVIEW

**Comment by Danbr4d** [comment]
I know this doesn't work but I'm a bit unsure how to access the input that I'm meant to be converting to int/bool. Also, do I try and change it to int before checking if it is the textWhenNull.

**Comment by Danbr4d** [comment]
I've also just realised I didn't rebase this before pushing so will sort that out too

File: src/keywords/optionalint.cpp [hunk 1]
```diff
@@ -55,9 +56,26 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
 // Deserialise from supplied LineParser, starting at given argument offset
 bool OptionalIntegerKeyword::deserialise(LineParser &parser, int startArg, const CoreData &coreData)
 {
+    try
+    {
+        std::stoi(data);
+    }
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:62]: So here you can just use the original (actually, fixed!) `parser.argi(startArg)` call to attempt the initial conversion.  This uses `stoi` so will throw an exception if it isn't a valid conversion.

```suggestion
    std::optional<int> newValue;
    try
    {
        newValue = parser.argi(startArg);
    }
```
If this succeeds (i.e. doesn't throw) then your `newValue` optional will contain the value to set.

File: src/keywords/optionalint.cpp [hunk 2]
```diff
@@ -55,9 +56,26 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
+        {
+            if (data == textWhenNull)
+                //here
+            else
+                DissolveSys::stob(data);
+        }
+        catch (...)
+        {
+        }
+    }
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:75]: Second part, there's no need to try/catch for the string conversion since we can do that as simple checks or conversions, this time using the string representation of the argument via `parser.argsv(startArg)`. If the string is neither the textWhenNull nor equates to `false` (via `DissolveSys::stob()`) then at this point we must return an error message since we don't know what to do with the input provided by the user.

**Comment by Danbr4d** [comment]
I think the error in the build is coming from DissolveSys::stob() but I'm not sure why

File: src/keywords/optionalint.cpp [hunk 3]
```diff
@@ -3,6 +3,7 @@
 
 #include "keywords/optionalint.h"
 #include "base/lineparser.h"
+#include "base/sysfunc.cpp"
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:6]: Eeek! That's not the header...
```suggestion
#include "base/sysfunc.h"
```

File: src/keywords/optionalint.cpp [hunk 4]
```diff
@@ -55,9 +56,28 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
+        newString = parser.argsv(startArg);
+        if (DissolveSys::stob(newString) == false)
+        {
+            if (newString != textWhenNull_)
+                Messenger::error("Unkonwn input, {}, provided\n", newString);
+            else
+                newString = textWhenNull_;
+        }
+        else
+            DissolveSys::stob(newString);
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:76]: The logic is a bit convoluted here, and after thinking about it I don't think we need to consider the `stob()` part.  I'd suggest removing the `newString` variable and doing something like:
```suggestion
        // Check explicitly for the null text
        if (DissolveSys::sameString(parser.argv(startArg), textWhenNull_))
            setData(std::nullopt);
        else
                return Messenger::error("Unknown input, {}, provided\n", newString);
```

File: src/keywords/optionalint.cpp [hunk 5]
```diff
@@ -55,9 +56,28 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
+    }
     if (parser.hasArg(startArg))
     {
-        auto x = parser.argd(startArg);
+        auto x = parser.argi(startArg);
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:80]: The guts of this bit can be moved into the `try` block, leaving just a `return true;` here (because we've handled all the errors earlier).

File: src/keywords/optionalint.cpp [hunk 6]
```diff
@@ -55,21 +56,32 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
 bool OptionalIntegerKeyword::deserialise(LineParser &parser, int startArg, const CoreData &coreData)
 {
-    if (parser.hasArg(startArg))
+    std::optional<int> newValue;
+    try
     {
-        auto x = parser.argd(startArg);
-        if (!setData(x))
+        newValue = parser.argi(startArg);
+        if (parser.hasArg(startArg))
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:63]: This check should actually be made with reverse logic (i.e. `if (!parser.hasArg.....`) as the very first thing we do in the function and immediately returning `false` since, if there's no argument to parse, there's no conversion to be made!

File: src/keywords/optionalint.cpp [hunk 7]
```diff
@@ -55,21 +56,32 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
         {
-            if (maximumLimit_)
-                Messenger::error("Value {} is out of range for keyword. Valid range is {} <= n.\n", x, maximumLimit_.value());
-
-            return false;
+            auto x = parser.argi(startArg);
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:65]: With the `if` check moved, you will be left with this bit of the function, and the `newValue` stuff can be removed.

File: src/keywords/optionalint.cpp [hunk 8]
```diff
@@ -55,21 +56,32 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
+            if (!setData(x))
+            {
+                if (maximumLimit_)
+                    Messenger::error("Value {} is out of range for keyword. Valid range is {} <= n.\n", x,
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:69]: I should have added the name of the keyword to the error message:
```suggestion
                    Messenger::error("Value {} is out of range for keyword '{}'. Valid range is {} <= n.\n", x, name_,
```

File: src/keywords/optionalint.cpp [hunk 9]
```diff
@@ -55,21 +56,32 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
         }
-
-        return true;
+    }
+    catch (...)
+    {
+        if (DissolveSys::sameString(parser.argsv(startArg), textWhenNull_))
+            setData(std::nullopt);
+        else
+            return Messenger::error("Unknown input, {}, provided\n", parser.argsv(startArg));
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:81]: We should make this error message consistent in content and format to the one above.

**Review by trisyoungs — COMMENTED** [review]
Pretty much there - just tidying.

File: src/keywords/optionalint.cpp [hunk 10]
```diff
@@ -48,28 +49,42 @@ int OptionalIntegerKeyword::valueDelta() const { return valueDelta_; }
 // Return text to display in widget  when value is null
 std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_; }
 
+// Return keyword name
+std::string_view KeywordBase::name() const { return name_; }
+
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:54]:
```suggestion
```

File: src/keywords/optionalint.cpp [hunk 11]
```diff
@@ -48,28 +49,42 @@ int OptionalIntegerKeyword::valueDelta() const { return valueDelta_; }
...
 bool OptionalIntegerKeyword::deserialise(LineParser &parser, int startArg, const CoreData &coreData)
 {
-    if (parser.hasArg(startArg))
+    try
     {
-        auto x = parser.argd(startArg);
+        if (!parser.hasArg(startArg))
+        {
+            return false;
+        }
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:67]: Stylistically, I prefer to not use curlies around simple statements like this when there's no need to enforce scope for what happens inside the braces.
```suggestion
            return false;
```

**Review by trisyoungs — COMMENTED** [review]
Small comments, but otherwise :+1: to move on to the `double` version and replicate.

File: src/keywords/optionaldouble.cpp [hunk 12]
```diff
@@ -55,21 +57,30 @@ std::string OptionalDoubleKeyword::textWhenNull() const { return textWhenNull_;
...
+
         auto x = parser.argd(startArg);
         if (!setData(x))
         {
             if (maximumLimit_)
-                Messenger::error("Value {} is out of range for keyword. Valid range is {} <= n.\n", x, maximumLimit_.value());
+                Messenger::error("Value {} is out of range for keyword '{}'. Valid range is {} <= n.\n", x, name(),
+                                 maximumLimit_.value());
 
             return false;
```
Comment (trisyoungs) [inline src/keywords/optionaldouble.cpp:72]: The `Messenger::error()` function returns `false` so we can do this:
```suggestion
                return Messenger::error("Value {} is out of range for keyword '{}'. Valid range is {} <= n.\n", x, name(),
                                        maximumLimit_.value());
```

File: src/keywords/optionalint.cpp [hunk 13]
```diff
@@ -55,21 +57,30 @@ std::string OptionalIntegerKeyword::textWhenNull() const { return textWhenNull_;
...
+        if (!parser.hasArg(startArg))
+            return false;
+
+        auto x = parser.argi(startArg);
         if (!setData(x))
         {
             if (maximumLimit_)
-                Messenger::error("Value {} is out of range for keyword. Valid range is {} <= n.\n", x, maximumLimit_.value());
+                Messenger::error("Value {} is out of range for keyword '{}'. Valid range is {} <= n.\n", x, name(),
+                                 maximumLimit_.value());
```
Comment (trisyoungs) [inline src/keywords/optionalint.cpp:70]: Use `return` here too.

**Review by trisyoungs — APPROVED** [review]
Small suggestion for neatness, otherwise :+1:.
